before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zip
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test
  - cd ..
  - |
    if [ -n "${TRAVIS_TAG}" ]; then
      cp -r src MotorShield &&
        zip -r MotorShield-${TRAVIS_TAG:1}.zip MotorShield
    fi
os:
  - linux
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: MotorShield-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  on:
    tags: true
