before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zip
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test
  - cd ..
  - cp -r src motor_shield
  - zip -r motor_shield.zip motor_shield
os:
  - linux
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: motor_shield.zip
  skip_cleanup: true
  on:
    tags: true
