before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zip
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test
  - cd ..
  - cp -r src MotorShield && zip -r MotorShield.zip MotorShield
os:
  - linux
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: MotorShield-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  on:
    tags: true
